spring.application.name=ingestion-service
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/flowmetrics
spring.datasource.username=flowmetrics
spring.datasource.password=flowmetrics_dev
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway ? let Spring know migrations are already handled externally
spring.flyway.enabled=false

# Disable JPA/datasource — ingestion service publishes to queue only, no direct DB writes
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=flowmetrics
spring.rabbitmq.password=flowmetrics_dev

# FlowMetrics ? GitHub webhook secret
flowmetrics.github.webhook-secret=d02c994c380b26fcf693e72e32166a47f40f23e42f8314012a33bd1aaa71f6ed


# Logging
logging.level.com.flowmetrics=DEBUG